# Generated by Django 3.0.3 on 2020-03-22 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nameId', models.CharField(max_length=20, unique=True)),
                ('year', models.SmallIntegerField()),
                ('semester', models.SmallIntegerField(verbose_name=[(1, 'semester 1'), (2, 'semester 2')])),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('nameId', models.CharField(max_length=20, unique=True)),
                ('modules', models.ManyToManyField(to='rating.Module')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Module')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Professor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.User')),
            ],
        ),
    ]
