# Generated by Django 3.0.3 on 2020-03-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='semester',
            field=models.SmallIntegerField(choices=[(1, 'semester 1'), (2, 'semester 2')]),
        ),
    ]
