# Generated by Django 3.0.3 on 2020-03-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_auto_20200322_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='nameId',
            field=models.CharField(max_length=20),
        ),
    ]
