# Generated by Django 3.0.3 on 2020-03-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_user_cookie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cookie',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
