# Generated by Django 3.0.3 on 2020-03-23 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0006_auto_20200323_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cookie',
        ),
    ]
