# Generated by Django 3.0.3 on 2020-03-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0007_remove_user_cookie'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cookie',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
