# Generated by Django 3.0.3 on 2020-03-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0008_user_cookie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='module',
        ),
    ]
